# Introduction to Numpy

In [1]:
##NumPy , which stands for Numerical python
import numpy as np #import numpy , np is an alias , we can use anything , it is just used to call numpy lib

In [4]:
#creating list
lis=[2,3,4,5,6,7,8,9]
print("Printing the list in list format",end=" ")
print(lis)
print("Printing the datatype list format",end=" ")
print(type(lis)) 
new_list = np.array(lis)  #typecasting list into numpy array, using np variable to call numpy lib and store it into the new variable
print(new_list)           #printing numpyarray
print(type(new_list))     #checking data type of the newly created variable of numpy array
print(new_list.shape)    #checking shape

Printing the list in list format [2, 3, 4, 5, 6, 7, 8, 9]
Printing the datatype list format <class 'list'>
[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(8,)


In [9]:
sq = np.arange(9)       #creating an array arange is used to create an array from 0-8 , 9 elements
print(sq)               #printing array
print(sq.ndim)          #telling dimension of array using ndim function
print(sq.shape)         #it will give the shape of array , we use shape function
print(sq.astype(float)) #we are typecasting array type to float type (elements of array get typecasted into float type), using astype function
print(sq.astype(int))   #we are typecasting array type to intt type (elements of array get typecasted into int type), using astype function
print(len(sq))          #len is used to count length of array

[0 1 2 3 4 5 6 7 8]
1
(9,)
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[0 1 2 3 4 5 6 7 8]
9


In [ ]:
#linspace function
"""start : starting value of sequence
stop : end value of sseq
num : number of samples/elements to be generated. Default is 50
Endpoint = if true(default) , stop value is last value.if false , stop value is not last value
"""       

In [11]:
np.linspace(1.0,5.0, num=4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [12]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [13]:
np.linspace(1.0,5.0,num = 5,endpoint =False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [15]:
#temp conversion using numpy array
temp = [25.3,55.3,98.5,50]
print("The temp list is : ")
print(temp)
print("The data type of list is : ")
print(type(temp))
newarray = np.array(temp)
print("The temp array after typecast is : ")
print(newarray)
print("The type of temp array is : ")
print(type(newarray))

carray = newarray*9/5 +32
print("The converted array is : ")
print(carray)
print("The type of converted array is : ")
print(type(carray))

The temp list is : 
[25.3, 55.3, 98.5, 50]
The data type of list is : 
<class 'list'>
The temp array after typecast is : 
[25.3 55.3 98.5 50. ]
The type of temp array is : 
<class 'numpy.ndarray'>
The converted array is : 
[ 77.54 131.54 209.3  122.  ]
The type of converted array is : 
<class 'numpy.ndarray'>


In [16]:
#without using numpy array
fvalues = [x*9/5 + 32 for x in temp] #this is list format
print(fvalues)

[77.54, 131.54, 209.3, 122.0]


In [18]:
sq = np.arange(24) #creating an array of 24 elements
print(sq) #printing
b = sq.reshape(2,3,4) #reshape is used to convert single dim array into 2 dim array - here (2 - number of matrix that needs to be created from 24 elements, 4 - number of rows,3 - number of columns)
print(b) #printing those matrix

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [44]:
sq = np.arange(32) #creating an array of 32 elements
print(sq) #printing
d = sq.reshape(1,4,8) #reshape is used to convert single dim array into 2 dim array - here (1 - number of matrix that needs to be created from 32 elements, 8 - number of rows,4 - number of columns)
print(d) #printing those matrix
e = sq.reshape(1,8,4)
print(e)
print(np.matmul(d,e)) #to multiply matrix in conventional form number of columns 1st matrix = number of rows of the 2nd matrix

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 560  588  616  644]
  [1456 1548 1640 1732]
  [2352 2508 2664 2820]
  [3248 3468 3688 3908]]]


In [22]:
sq = np.arange(32) #creating an array of 32 elements
print(sq) #printing
c = sq.reshape(2,4,4) #reshape is used to convert single dim array into 2 dim array - here (2 - number of matrix that needs to be created from 32 elements, 4 - number of rows,4 - number of columns)
print(c) #printing those matrix
print(c+c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]
  [24 26 28 30]]

 [[32 34 36 38]
  [40 42 44 46]
  [48 50 52 54]
  [56 58 60 62]]]


In [38]:
#how to add values to a matrix
know = np.array([4,5,8])
print(know)
how = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(how)
print(know*how)

[4 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4 10 24]
 [16 25 48]
 [28 40 72]]


In [42]:
W = np.ones((3,4)) #it will create matrix of ones
print(W)
m = np.ones([3,4]) # it will work for list type array also ie square brackets
#we can also change the data type of ones matrix
l = np.ones((3,4) , dtype = int) #dtype will convert the by default float type to int type but for random matrix it doesn't work random matrix will always be in float
print(l)
X = np.random.random([4,3]) #random function will randomly create a 4*3 matrix with random flaot elements
print(X)  
Y = np.random.random([4,3]) #it will throw error when number of rows and columns that needs to be added are different
print(Y)
s = np.add(X,Y) # we can also us X+Y
print(s)
print(X-Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0.58163479 0.67186697 0.71775816]
 [0.22858556 0.98124281 0.36249169]
 [0.05250998 0.48526589 0.93323032]
 [0.86826646 0.76228356 0.98669891]]
[[0.42662227 0.86348596 0.61812455]
 [0.61247613 0.28163184 0.99408158]
 [0.01716972 0.34750798 0.343606  ]
 [0.60766638 0.0490193  0.46945032]]
[[1.00825706 1.53535293 1.33588272]
 [0.84106169 1.26287466 1.35657327]
 [0.06967969 0.83277386 1.27683633]
 [1.47593285 0.81130286 1.45614923]]
[[ 0.15501253 -0.19161898  0.09963361]
 [-0.38389058  0.69961097 -0.63158989]
 [ 0.03534026  0.13775791  0.58962432]
 [ 0.26060008  0.71326426  0.51724858]]


In [47]:
data= np.array([5,4,0,8,8,9,6,7,8,2])
print(data)
print(data.mean())
print(np.max(data))
print(np.min(data))
print(np.std(data)) #standard deviation
print(np.median(data))
print(np.var(data)) #variance
#mode is not supported

[5 4 0 8 8 9 6 7 8 2]
5.7
9
0
2.794637722496424
6.5
7.81


In [48]:
#dot product
f= np.array([1,2])
g= np.array([4,5])
np.dot(f,g) #1*4 +2*5

14

In [ ]:
#min dimension


In [50]:
#resize - resize is not transpose
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [53]:
##create a new data type
i16=np.dtype(np.int16) #like int16 , there are int32, int64 we can increase the bit size
#i16
print(i16)

##creating a list
fst = [[3.4,8.7,9.9],[1.1,-7.8,-0.7],[4.1,123,4.8]]

#create a array with input list n datatype the newly created one
A=np.array(fst,dtype=i16)
#A=np.array(fst,dtype=np.int16) - this will also give the same result - we can use this directly
print(A)

int16
[[  3   8   9]
 [  1  -7   0]
 [  4 123   4]]


In [54]:
student = np.dtype([('name','S10'),('age','i8'),('marks','f8')])
print(student)

a=np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a)

print(a['name'])

[('name', 'S10'), ('age', '<i8'), ('marks', '<f8')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[b'abc' b'xyz']


In [57]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('\n')
print('The items in the second column are ')
print(a[..., 1])
print('\n')

print('The items in the second row are ')
print(a[1,...])
print('\n')
print('The items in the column 1 onwards are ')
print(a[...,1:])
print('\n')
print('The items in the row 1 onwards are ')
print(a[1:,...]) #or (a[1:,:]) will also give the same answer
print('\n')

[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are 
[2 4 5]


The items in the second row are 
[3 4 5]


The items in the column 1 onwards are 
[[2 3]
 [4 5]
 [5 6]]


The items in the row 1 onwards are 
[[3 4 5]
 [4 5 6]]




In [58]:
#broadcasting
A= np.array([(1,2),(3,4)])
B= np.array([1,2])
print("matrix a :")
print(A)

print("matrix b : ")
print(B)

print("multiplication with broadcasting : ")
print(A*B)

print("now addition using broadcasting")
print(A+B)


matrix a :
[[1 2]
 [3 4]]
matrix b : 
[1 2]
multiplication with broadcasting : 
[[1 4]
 [3 8]]
now addition using broadcasting
[[2 4]
 [4 6]]


In [60]:
#flatten
A.flatten() # it will flatten the 2d array into one dim

array([1, 2, 3, 4])

In [63]:
#stack n vstack
f= np.array([1,2,3])
g=np.array([4,5,6])

print("horizontal append ", np.hstack((f,g)))
print("vertical append \n ", np.vstack((f,g)))

horizontal append  [1 2 3 4 5 6]
vertical append 
  [[1 2 3]
 [4 5 6]]


In [101]:
def med(lis):
    
    ls=sorted(lis)
    print(ls)
    n=len(ls)
    print(n)
    h=n//2
##print(h)
##hh=(n/2)+1
##m = int(ls[h])
#print(m)
    if(n%2 ==0):
            med=(ls[h]+ls[h+1])/2
            print("median is : " , med)
    else:
            med=ls[h+1]
            print("median is : " , med)

lis = [3,2,5,1,6,4]
med(lis)
            
          
        
    
    


[1, 2, 3, 4, 5, 6]
6
median is :  4.5


In [103]:
def central(ls):
 
    sot=sorted(ls)
    print(sot)
    n=len(sot)
    mid=n//2
    print("the 3 central values are : ")
    print(sot[mid-1])
    print(sot[mid])
    print(sot[mid+1])

ls=[40,20,60,80,86]
central(ls)

[20, 40, 60, 80, 86]
the 3 central values are : 
40
60
80
